### ISSUE TITLE
VPC and subnets get created but the RDS creation fails

### ISSUE THREAD

**Issue by santiagocardenas** [aws-quickstart/quickstart-alfresco-content-services#12]
@pele7208 commented:
Hi,
VPC and subnets get created but the RDS creation fails with
"Cannot create a db.t2.small Multi-AZ instance because at least 2 subnets must exist in availability zones with sufficient capacity for VPC and storage type : standard for db.t2.small, so 1 more must be created in other availability zones; choose from these availability zones: us-east-1c, us-east-1d, us-east-1e."
I specified us-east-1a and us-east-1b as my AZs and I can see the subnets are created. Any ideas?
Thanks

@toniblyx replied:
Hi, thanks for letting us know. It seems to be an error related to either your account limits or your VPC configuration, but if you have a correct VPC configuration might be your limits or permissions. Please can you check if everything is fine in Trusted Advisor?
      
@pele7208 replied:
Thanks for the quick response. The template creates the VPC and subnets correctly. I see them listed in AWS and the Cloudformation succeeds on that step. I checked Trusted Advisor and don't see any problems. This is a corporate AWS account and I'm using an administrator account. BTW, I was able to create the cluster using an existing VPC. I would like to be able to do it with a new VPC. Thanks.

@toniblyx replied:
I'm wondering if it is something else we missed. Can you contact AWS support in case they see something else? Don't know if @santiagocardenas has seen that error before in other templates.

**Comment by santiagocardenas** [comment]
So from time to time, you may run into Availability Zones that may have limited capacity for an instance type when a customer tries to launch it. This can be addressed with purchasing reserved instance capacity. However, in this case I would just suggest you use different Availability Zones as indicated by the insufficient capacity error message.

**Comment by pele7208** [comment]
I switched AZs to us-east-1d and us-east-1e and it worked.  I took not enough capacity error to mean not enough IP addresses in the VPC which confused me.  So what they are really saying is not enough hardware/infrastructure available?  Thanks for all your help.

**Comment by pele7208** [comment]
BTW, I noticed I only have one bastion server.  The documentation and the tutorial video say two would be created.

**Comment by santiagocardenas** [comment]
Yes, you caught us right in a transition stage where the product is renamed to Alfresco Content Services. At the same time, the Linux bastion Quick Start was updated to harden its security plus deploy a single instance (by default) in an auto-scaling group. This means that if the instance is deleted, a new one is brought up with the same elastic IP. The documentation and diagrams will be updated to reflect that.

**Comment by pele7208** [comment]
Do you have any pre-baked Alfresco with solr AMIs that I can use? I would like a cluster without separating the Alfresco and Index servers.  Thanks.

**Comment by toniblyx** [comment]
Hi @pele7208, our official Marketplace AMI has Solr and Alfresco One (now Content Services). Also this QuickStart deployment configures the index layer with Alfresco repo and Solr in the same box (using Alfresco repo as index tracking) as we recommend at Alfresco.

**Comment by pele7208** [comment]
Hi.  I'm trying to avoid having a separate index layer.  Basically combine the Alfresco and Index server on same server. Is that not possible with a cluster configuration?

**Comment by toniblyx** [comment]
It is possible with a customized template and also changing the json file configuration that makes chef to reconfigure everything.

**Comment by pele7208** [comment]
Hi. Is this cluster setup the same for Alfresco 5.0.2?

**Comment by toniblyx** [comment]
Alfresco software configuration is pretty much the same for 5.2 and 5.1 (previous AMI). Remember you don't have to set up anything since it will be configured automatically by chef-alfresco.

**Comment by pele7208** [comment]
Hi.  If I'm editing a document on one server and the server goes down, should one of the other servers take over and save any edits I made while connected to the original server.

**Comment by toniblyx** [comment]
Hi @pele7208, actually you don't edit a document on a server but you have a session on a cluster node. Alfresco takes care of the changes and cache clustering but if you need session replication you need to implement it in Tomcat or Elasticache. See this for more information: https://github.com/magro/memcached-session-manager

**Comment by pele7208** [comment]
Can you elaborate on "Alfresco takes care of the changes and cache clustering"? Thanks.

**Comment by toniblyx** [comment]
You can check out our official documentation about HA to clarify it and other questions about clustering http://docs.alfresco.com/5.2/concepts/ha-intro.html

**Comment by pele7208** [comment]
Isn't a load balancer sufficient to take care of redundancy?   Is alfresco clustering just a matter of a license allowing it?  You have to use sticky sessions which means always connect to the same server right?

**Comment by toniblyx** [comment]
Load balancer with sticky sessions is to prevent session balancing since it is not configured by default. Exactly, to make Alfresco work in cluster, you need a clustering enabled license in order to use it.

**Comment by pele7208** [comment]
Thanks.  Any plans on making Tomcat session replication setup part of the CloudFormation setup? I think that would be very useful.

**Comment by toniblyx** [comment]
I agree with you. I will send this suggestion to the product manager behind this project. Thanks.

**Comment by pele7208** [comment]
Cool.  BTW, the session replication with memcached worked pretty well.

**Comment by toniblyx** [comment]
Nice! Glad to hear that, thanks for your feedback @pele7208
